import type { College } from "./types";

export const MOCK_COLLEGES: College[] = [
  {
    id: "mit",
    name: "Massachusetts Institute of Technology",
    location: { state: "MA", city: "Cambridge", lat: 42.3601, lon: -71.0942 },
    type: "private",
    size: 4657,
    admission_rate: 0.041,
    sat_25: 1520,
    sat_75: 1580,
    gpa_50: 3.95,
    tuition: 60390,
    has_merit_aid: false,
    top_majors: ["Computer Science", "Electrical Engineering", "Mechanical Engineering", "Mathematics"],
    cds_factors: {
      rigor: "very_important", gpa: "very_important", test_scores: "very_important",
      essays: "very_important", recommendations: "very_important", ecs: "very_important",
      demonstrated_interest: "not_considered", first_gen: "considered", legacy: "not_considered",
    },
  },
  {
    id: "stanford",
    name: "Stanford University",
    location: { state: "CA", city: "Stanford", lat: 37.4275, lon: -122.1697 },
    type: "private",
    size: 7645,
    admission_rate: 0.036,
    sat_25: 1500,
    sat_75: 1570,
    gpa_50: 3.96,
    tuition: 62484,
    has_merit_aid: false,
    top_majors: ["Computer Science", "Engineering", "Biology", "Economics"],
    cds_factors: {
      rigor: "very_important", gpa: "very_important", test_scores: "considered",
      essays: "very_important", recommendations: "very_important", ecs: "very_important",
      demonstrated_interest: "not_considered", first_gen: "considered", legacy: "considered",
    },
  },
  {
    id: "harvard",
    name: "Harvard University",
    location: { state: "MA", city: "Cambridge", lat: 42.3770, lon: -71.1167 },
    type: "private",
    size: 7240,
    admission_rate: 0.034,
    sat_25: 1490,
    sat_75: 1580,
    gpa_50: null,
    tuition: 59076,
    has_merit_aid: false,
    top_majors: ["Economics", "Computer Science", "Political Science", "Biology"],
    cds_factors: {
      rigor: "very_important", gpa: "very_important", test_scores: "important",
      essays: "very_important", recommendations: "very_important", ecs: "very_important",
      demonstrated_interest: "not_considered", first_gen: "considered", legacy: "considered",
    },
  },
  {
    id: "uc-berkeley",
    name: "University of California, Berkeley",
    location: { state: "CA", city: "Berkeley", lat: 37.8719, lon: -122.2585 },
    type: "public",
    size: 32831,
    admission_rate: 0.117,
    sat_25: null,
    sat_75: null,
    gpa_50: 3.89,
    tuition: 46326,
    has_merit_aid: true,
    top_majors: ["Computer Science", "Economics", "Molecular & Cell Biology", "Data Science"],
    cds_factors: {
      rigor: "very_important", gpa: "very_important", test_scores: "not_considered",
      essays: "very_important", recommendations: "not_considered", ecs: "very_important",
      demonstrated_interest: "not_considered", first_gen: "important", legacy: "not_considered",
    },
  },
  {
    id: "umich",
    name: "University of Michigan",
    location: { state: "MI", city: "Ann Arbor", lat: 42.2780, lon: -83.7382 },
    type: "public",
    size: 32695,
    admission_rate: 0.179,
    sat_25: 1360,
    sat_75: 1530,
    gpa_50: 3.9,
    tuition: 57273,
    has_merit_aid: true,
    top_majors: ["Computer Science", "Business", "Engineering", "Psychology"],
    cds_factors: {
      rigor: "very_important", gpa: "very_important", test_scores: "important",
      essays: "very_important", recommendations: "important", ecs: "important",
      demonstrated_interest: "not_considered", first_gen: "considered", legacy: "considered",
    },
  },
  {
    id: "gatech",
    name: "Georgia Institute of Technology",
    location: { state: "GA", city: "Atlanta", lat: 33.7756, lon: -84.3963 },
    type: "public",
    size: 17842,
    admission_rate: 0.162,
    sat_25: 1370,
    sat_75: 1530,
    gpa_50: 4.02,
    tuition: 33794,
    has_merit_aid: true,
    top_majors: ["Computer Science", "Mechanical Engineering", "Industrial Engineering", "Business"],
    cds_factors: {
      rigor: "very_important", gpa: "very_important", test_scores: "important",
      essays: "important", recommendations: "considered", ecs: "important",
      demonstrated_interest: "not_considered", first_gen: "considered", legacy: "not_considered",
    },
  },
  {
    id: "williams",
    name: "Williams College",
    location: { state: "MA", city: "Williamstown", lat: 42.7128, lon: -73.2036 },
    type: "private",
    size: 2138,
    admission_rate: 0.085,
    sat_25: 1450,
    sat_75: 1550,
    gpa_50: 3.9,
    tuition: 63200,
    has_merit_aid: false,
    top_majors: ["Economics", "Mathematics", "Political Science", "Biology"],
    cds_factors: {
      rigor: "very_important", gpa: "very_important", test_scores: "important",
      essays: "very_important", recommendations: "very_important", ecs: "very_important",
      demonstrated_interest: "considered", first_gen: "important", legacy: "considered",
    },
  },
  {
    id: "ut-austin",
    name: "University of Texas at Austin",
    location: { state: "TX", city: "Austin", lat: 30.2849, lon: -97.7341 },
    type: "public",
    size: 42444,
    admission_rate: 0.31,
    sat_25: 1230,
    sat_75: 1480,
    gpa_50: null,
    tuition: 41070,
    has_merit_aid: true,
    top_majors: ["Business", "Computer Science", "Biology", "Communications"],
    cds_factors: {
      rigor: "very_important", gpa: "very_important", test_scores: "considered",
      essays: "important", recommendations: "considered", ecs: "important",
      demonstrated_interest: "not_considered", first_gen: "considered", legacy: "not_considered",
    },
  },
  {
    id: "ohio-state",
    name: "The Ohio State University",
    location: { state: "OH", city: "Columbus", lat: 39.9990, lon: -83.0111 },
    type: "public",
    size: 47090,
    admission_rate: 0.53,
    sat_25: 1300,
    sat_75: 1460,
    gpa_50: 3.87,
    tuition: 37282,
    has_merit_aid: true,
    top_majors: ["Business", "Psychology", "Engineering", "Biology"],
    cds_factors: {
      rigor: "important", gpa: "very_important", test_scores: "important",
      essays: "considered", recommendations: "considered", ecs: "considered",
      demonstrated_interest: "considered", first_gen: "considered", legacy: "considered",
    },
  },
  {
    id: "asu",
    name: "Arizona State University",
    location: { state: "AZ", city: "Tempe", lat: 33.4242, lon: -111.9281 },
    type: "public",
    size: 65174,
    admission_rate: 0.88,
    sat_25: 1130,
    sat_75: 1360,
    gpa_50: 3.58,
    tuition: 32193,
    has_merit_aid: true,
    top_majors: ["Business", "Engineering", "Psychology", "Communications"],
    cds_factors: {
      rigor: "important", gpa: "very_important", test_scores: "considered",
      essays: "considered", recommendations: "not_considered", ecs: "considered",
      demonstrated_interest: "not_considered", first_gen: "considered", legacy: "not_considered",
    },
  },
];

export function getCollegeById(id: string): College | undefined {
  return MOCK_COLLEGES.find((c) => c.id === id);
}
